package challenge.upnid.constants;

public enum RejectCode {
	NEW_USER_BIG_TRANSACTION,
	NEW_USER_TOO_MANY_TRANSACTIONS,
	SUSPECT_INTERNATIONAL_SHIṔPING,
	MANY_TRANSACTIONS_IN_SHORT_TIME,
	TOO_MANY_CARDS_TO_SAME_ADDRRES
}
